root: ./docs-api/

​structure:
    readme: README.md
    summary: SUMMARY.md​

redirects:
    frontity-cli/environment-variables: ./frontity-cli/README.md
    frontity-packages/frontity: ./frontity-packages/core-package/frontity.md
    frontity-packages/frontity-analytics: ./frontity-packages/features-packages/analytics/README.md
    frontity-packages/router: ./frontity-packages/features-packages/tiny-router.md
    frontity-packages/wordpress-source: ./frontity-packages/features-packages/wp-source.md
    frontity-packages/frontity-html2react: ./frontity-packages/features-packages/html2react.md
    frontity-packages/frontity-components: ./frontity-packages/collections-packages/components.md
    frontity-packages/frontity-hooks: ./frontity-packages/collections-packages/hooks.md
    frontity-themes: ./frontity-packages/themes-packages/README.md
    frontity-themes/frontity-mars-theme: ./frontity-packages/themes-packages/frontity-mars-theme.md
    frontity-themes/frontity-twentytwenty-theme: ./frontity-packages/themes-packages/frontity-twentytwenty-theme.md

    